In [8]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')
import hvplot.pandas

ModuleNotFoundError: No module named 'panel'

In [6]:
data = pd.read_csv('demo2.csv')

In [11]:
data

,Unnamed: 0,STATE_UT_NAME,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,...,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec,flood,Avg_june10days,maytojune
0,0,ANDAMAN And NICOBAR ISLANDS,107.3,57.9,65.2,117.0,358.5,295.5,285.0,271.9,...,315.2,250.9,2805.2,165.2,540.7,1207.2,892.1,0,98.500000,63.0
1,1,ANDAMAN And NICOBAR ISLANDS,43.7,26.0,18.6,90.5,374.4,457.2,421.3,423.1,...,275.8,128.3,3015.7,69.7,483.5,1757.2,705.3,0,152.400000,82.8
2,2,ANDAMAN And NICOBAR ISLANDS,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,...,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7,0,167.766667,159.7
3,3,ARUNACHAL PRADESH,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,...,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0,0,149.000000,140.6
4,4,ARUNACHAL PRADESH,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,...,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1,1,246.100000,415.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,636,KERALA,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,...,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2,0,217.200000,419.0
637,637,KERALA,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,...,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9,1,333.200000,782.0
638,638,KERALA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,...,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2,0,185.633333,262.2
639,639,KERALA,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,...,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5,1,232.700000,523.5
640,640,LAKSHADWEEP,20.8,14.7,11.8,48.9,171.7,330.2,287.7,217.5,...,117.7,58.8,1600.0,35.5,232.4,998.5,333.6,0,110.066667,158.5

In [13]:
data.columns

Index(['Unnamed: 0', 'STATE_UT_NAME', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
       'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb',
       'Mar-May', 'Jun-Sep', 'Oct-Dec', 'flood', 'Avg_june10days',
       'maytojune'],
      dtype='object')

In [15]:
data[data['STATE_UT_NAME'] == 'ANDHRA PRADESH']

,Unnamed: 0,STATE_UT_NAME,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,...,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec,flood,Avg_june10days,maytojune
537,537,ANDHRA PRADESH,6.0,10.1,11.3,22.8,75.3,131.9,206.4,188.4,...,69.8,7.8,1106.0,16.1,109.4,703.9,276.6,0,43.966667,56.6
538,538,ANDHRA PRADESH,6.1,10.7,8.7,19.0,55.8,135.8,240.2,227.8,...,66.7,11.7,1160.4,16.8,83.5,783.9,276.2,0,45.266667,80.0
539,539,ANDHRA PRADESH,5.5,7.7,7.7,15.0,58.4,90.2,147.3,155.4,...,75.8,14.5,871.5,13.2,81.1,543.0,234.2,0,30.066667,31.8
540,540,ANDHRA PRADESH,4.6,6.3,8.7,16.9,46.8,120.9,216.6,194.2,...,66.1,12.1,1027.1,10.9,72.4,701.4,242.4,0,40.300000,74.1
541,541,ANDHRA PRADESH,15.7,11.6,6.0,15.2,51.4,53.4,91.2,95.0,...,283.9,107.2,1091.6,27.3,72.6,352.4,639.3,0,17.800000,2.0
542,542,ANDHRA PRADESH,7.9,8.8,10.5,14.9,52.3,64.3,99.3,95.9,...,115.0,32.1,805.9,16.7,77.7,382.5,329.0,0,21.433333,12.0
543,543,ANDHRA PRADESH,7.9,18.1,17.2,26.3,63.9,145.0,190.2,202.4,...,69.8,4.9,1165.2,26.0,107.4,745.7,286.1,0,48.333333,81.1
544,544,ANDHRA PRADESH,8.8,10.8,17.6,44.7,96.6,132.6,178.2,178.2,...,59.2,4.3,1120.7,19.6,158.9,674.4,267.8,0,44.200000,36.0
545,545,ANDHRA PRADESH,8.7,14.4,17.7,32.3,90.7,140.7,181.5,194.8,...,56.3,6.1,1140.4,23.1,140.7,726.1,250.5,0,46.900000,50.0
546,546,ANDHRA PRADESH,7.5,7.0,11.4,11.9,18.2,178.4,317.4,291.7,...,14.8,7.3,1120.0,14.5,41.5,958.9,105.1,0,59.466667,160.2
547,547,ANDHRA PRADESH,5.9,7.4,14.6,20.4,33.8,110.7,176.8,190.5,...,23.7,6.4,851.3,13.3,68.8,643.5,125.7,0,36.900000,76.9
548,548,ANDHRA PRADESH,10.8,5.6,10.8,15.7,24.0,153.2,257.3,226.7,...,20.8,5.9,979.8,16.4,50.5,800.3,112.6,0,51.066667,129.2
549,549,ANDHRA PRADESH,4.5,7.1,10.6,23.8,52.6,150.3,282.8,256.4,...,24.5,4.5,1094.9,11.6,87.0,860.4,135.9,0,50.100000,97.7
550,550,ANDHRA PRADESH,1.8,2.9,5.6,16.6,34.1,91.1,161.6,158.2,...,21.2,3.8,731.1,4.7,56.3,559.7,110.4,0,30.366667,57.0
551,551,ANDHRA PRADESH,6.5,4.9,9.5,18.8,28.0,138.2,229.4,211.1,...,19.3,4.8,922.3,11.4,56.3,743.9,110.7,0,46.066667,110.2
552,552,ANDHRA PRADESH,4.1,4.3,9.2,15.1,28.7,103.2,154.7,147.2,...,32.0,6.6,760.5,8.4,53.0,554.7,144.4,0,34.400000,74.5
553,553,ANDHRA PRADESH,7.9,4.4,8.8,12.3,24.5,161.3,289.4,296.5,...,17.1,5.5,1091.9,12.3,45.6,920.1,113.9,0,53.766667,136.8
554,554,ANDHRA PRADESH,8.3,7.8,12.3,14.2,28.7,147.6,271.2,222.3,...,22.9,7.2,986.9,16.1,55.2,796.6,119.0,0,49.200000,118.9
555,555,ANDHRA PRADESH,3.1,4.0,7.4,21.1,34.6,109.4,190.6,176.5,...,19.1,4.3,841.8,7.1,63.1,653.7,117.9,0,36.466667,74.8
556,556,ANDHRA PRADESH,3.0,3.3,6.1,18.9,56.7,55.2,64.3,74.5,...,35.3,11.6,572.7,6.3,81.7,322.8,161.9,0,18.400000,1.5
557,557,ANDHRA PRADESH,7.7,7.6,10.1,25.6,67.2,66.8,100.1,110.2,...,137.3,58.4,898.2,15.3,102.9,417.1,362.9,0,22.266667,0.4
558,558,ANDHRA PRADESH,1.9,2.4,4.7,17.3,47.6,69.8,101.1,108.6,...,77.2,24.4,716.9,4.3,69.6,404.1,238.9,0,23.266667,22.2
559,559,ANDHRA PRADESH,1.2,1.9,5.7,18.3,51.7,80.5,115.8,124.3,...,28.4,6.6,679.6,3.1,75.7,460.2,140.6,0,26.833333,28.8

In [22]:
template = pn.template.FastListTemplate(
    title = 'Flood Dashboard',
    sidebar=[pn.pane.Markdown("#flood prediction"),
             pn.pane.Markdown("###This is te flood prediction page"),
             pn.pane.JPG('img.jpg', sizing_mode='scale_both'),
             pn.pane.Markdown("##settings"),
             month_slider],
    main=[pn.Row(pn.column(yaxis_co2,
                           co2_plot.panel(wdith=700), margin=(0,25)),
                 co2_table.panel(width=500)),
          pn.Row(pn.Coloumn(co2_vs_gdp_scatterplot.panel(width=600), margin=(0,25)),
                 pn.Coloumn(yaxis_co2_source_bar_plot.panel(width=600)))],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)
# template.show()
template.servable();

NameError: name 'month_slider' is not defined